export type RevenueStream = 'transaction' | 'commission_protection' | 'subscription' | 'document_verification' | 'document_generation' | 'premium_listing' | 'intelligence';
export type SubscriptionPlan = 'free' | 'mandate_pro' | 'facilitator_pro' | 'enterprise';
export type VerificationItem = 'BCL' | 'SGS' | 'POP' | 'KYC';
export type ListingTerm = '7d' | '30d';
export interface RevenueQuote { stream: RevenueStream; code: string; description: string; currency: string; amount: number; basis: string; payable: boolean; }
export const TRANSACTION_FEE_RANGE = { minPct: 0.75, maxPct: 1.5 } as const;
export const COMMISSION_PROTECTION = { pct: 0.25, flatZar: 5000 } as const;
export const SUBSCRIPTION_PRICES_ZAR: Record<SubscriptionPlan, number> = { free: 0, mandate_pro: 1500, facilitator_pro: 2500, enterprise: 10000 };
export const VERIFICATION_PRICES_ZAR: Record<VerificationItem, number> = { BCL: 2500, SGS: 3500, POP: 1500, KYC: 7500 };
export const LISTING_PRICES_ZAR: Record<ListingTerm, number> = { '7d': 2000, '30d': 5000 };
export function percentageFee(base:number,pct:number){return Number.isFinite(base)&&base>=0&&Number.isFinite(pct)&&pct>=0?Math.round(base*(pct/100)*100)/100:0}
export function quoteTransaction(base:number,pct=0.75,currency='USD'):RevenueQuote{if(pct<0.75||pct>1.5)throw new Error('Transaction fee must be between 0.75% and 1.5%.');return{stream:'transaction',code:'TRANSACTION_SERVICE',description:'Escrow/transaction service fee',currency,amount:percentageFee(base,pct),basis:pct+'% of deal value at the configured transaction-service rate',payable:true}}
export function quoteCommissionProtection(base:number,mode:'percentage'|'flat'='percentage'):RevenueQuote{const amount=mode==='percentage'?percentageFee(base,0.25):5000;return{stream:'commission_protection',code:'COMMISSION_PROTECTION',description:'Commission-chain protection fee',currency:'ZAR',amount,basis:mode==='percentage'?'0.25% of protected commission basis':'Flat R5,000 protection fee',payable:true}}
export function quoteSubscription(plan:SubscriptionPlan):RevenueQuote{return{stream:'subscription',code:'SUB_'+plan.toUpperCase(),description:plan.replace('_',' ')+' subscription',currency:'ZAR',amount:SUBSCRIPTION_PRICES_ZAR[plan],basis:'Monthly subscription',payable:plan!=='free'}}
export function quoteVerification(item:VerificationItem):RevenueQuote{return{stream:'document_verification',code:'VERIFY_'+item,description:item+' verification',currency:'ZAR',amount:VERIFICATION_PRICES_ZAR[item],basis:'Per verification request',payable:true}}
export function quoteDocumentPack():RevenueQuote{return{stream:'document_generation',code:'NCNDA_IMFPA_PACK',description:'NCNDA/IMFPA generation pack',currency:'ZAR',amount:1500,basis:'Per populated deal/commission-chain pack',payable:true}}
export function quotePremiumListing(term:ListingTerm):RevenueQuote{return{stream:'premium_listing',code:'LISTING_'+term.toUpperCase(),description:'Premium commodity listing',currency:'ZAR',amount:LISTING_PRICES_ZAR[term],basis:term==='7d'?'7-day listing':'30-day listing',payable:true}}
export function quoteIntelligence(base:number,currency='ZAR'):RevenueQuote{return{stream:'intelligence',code:'INTELLIGENCE_FINDER',description:'Data/intelligence lead-generation finder fee',currency,amount:percentageFee(base,1),basis:'1% finder fee on the applicable lead/deal basis',payable:true}}
export function quoteAllApprovedStreams(input:{dealValue:number;protectedCommissionBasis?:number;transactionPct?:number;transactionCurrency?:string;subscription?:SubscriptionPlan;verification?:VerificationItem;listing?:ListingTerm;intelligenceBasis?:number}):RevenueQuote[]{const q:RevenueQuote[]=[];if(input.dealValue>0)q.push(quoteTransaction(input.dealValue,input.transactionPct,input.transactionCurrency));if(input.protectedCommissionBasis!==undefined)q.push(quoteCommissionProtection(input.protectedCommissionBasis));if(input.subscription)q.push(quoteSubscription(input.subscription));if(input.verification)q.push(quoteVerification(input.verification));q.push(quoteDocumentPack());if(input.listing)q.push(quotePremiumListing(input.listing));if(input.intelligenceBasis!==undefined)q.push(quoteIntelligence(input.intelligenceBasis));return q}
